task:
  environment:
    CACHIX_SIGNING_KEY: ENCRYPTED[1d52a0656368529f85baf6c07f1814c4b1efd8c837643418b988dfe2bf257c23d3a0a84e21d33cc7232507434907fe10]
    # Save some traffic by excluding the full git history
    CIRRUS_CLONE_DEPTH: 1

  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  container:
    # Defined in https://github.com/nix-community/docker-nixpkgs
    image: nixpkgs/nix-flakes:nixos-24.11

  matrix:
    - name: modules_test
      container:
        # Besides virtualization, this also enables privileged containers which are required for
        # sandboxed builds
        kvm: true
        # Needed for package builds
        memory: 8G
        # A maximum of 16 CPUs is shared among all concurrent tasks.
        # https://cirrus-ci.org/faq/#are-there-any-limits
        cpu: 4
      environment:
        matrix:
          - scenario: default
      # This script is run as root
      build_script:
        - printf '%s\n' 'sandbox = true' 'max-jobs = auto' >> /etc/nix/nix.conf
        - nix shell --inputs-from . nixpkgs#{bash,coreutils,cachix} -c ./test/ci/build.sh $scenario

    - name: flake
      build_script:
        - nix flake check --all-systems
        - ./test/nixos-search/ci-test.sh

    - name: shellcheck
      build_script:
        - ./test/shellcheck.sh
