# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    charge-lnd
    electrs
    elementsd
    extra-container
    fulcrum
    hwi
    lightning-pool
    lndconnect;

  inherit (pkgsUnstable)
    btcpayserver
    clightning
    lightning-loop
    nbxplorer;

  inherit pkgs pkgsUnstable;
}
