# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    electrs
    elementsd
    extra-container
    lightning-pool
    lndconnect
    nbxplorer;

  inherit (pkgsUnstable)
    btcpayserver
    charge-lnd
    fulcrum
    hwi
    lightning-loop
    lnd
    lndhub-go;

  inherit pkgs pkgsUnstable;
}
