# This file is generated by ../helper/update-flakes.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    lndconnect;

  inherit (pkgsUnstable)
    btcpayserver
    charge-lnd
    clightning
    electrs
    elementsd
    hwi
    lightning-loop
    lightning-pool
    lnd
    nbxplorer;

  inherit pkgs pkgsUnstable;
}
